### ISSUE TITLE
Unable to decrypt using symbolocatecrash

### ISSUE THREAD

**Issue by LaheCloud** [tomieq/AppleCrashScripts#2]
hello,I can't use symbolicatecrash to decrypt using the translated ips/crash file, it will show

`No crash report version in {ips/crash_file} at ./symbolicatecrash line 1365.`

**Comment by tomieq** [comment]
Hello LaheCloud,
Could you please provide the console output of the full command you invoke? (the one starting with  `swift symbolicate.swift -crash`)

**Comment by LaheCloud** [comment]
hxz邮箱已收到您发的邮件！

**Comment by LaheCloud** [comment]
`Working in /Users/xxxxxxx/Downloads/AppleCrashScripts`
`---------------------------------------`
`Found 1 DWARF files in working directory:
{ UUID: 3133F031-684B-34B9-9A9B-45673487C225, arch: arm64, dSYMFileName: xxxxxx.app.dSYM }`
`---------------------------------------`
`Error Domain=NSCocoaErrorDomain Code=256 "The file “AppleCrashScripts” couldn’t be opened." UserInfo={NSFilePath=/Users/xxxxxxx/Downloads/AppleCrashScripts/., NSUnderlyingError=0x600003230270 {Error Domain=NSPOSIXErrorDomain Code=21 "Is a directory"}}`

Thanks for your reply, the above is the output information.
I found a new way, use the **CrashSymbolicator.py** that comes with Xcode to decrypt first, and then use your script to view the information!

**Comment by LaheCloud** [comment]
I know where the problem is Crash translated using convertFromJSON is missing this keyword
`Report Version:`
hope it gets resolved

**Comment by tomieq** [comment]
That was my first thought, but I studied the official documentation and could not find this field (https://developer.apple.com/documentation/xcode/examining-the-fields-in-a-crash-report).

Did you make it working after adding field `Report Version:`?
If yes, what value did you set for this field? In the converter we can set some default value, but please provide working one.

**Comment by LaheCloud** [comment]
I have tried adding `Report Version:             104` which can be decrypted using the old method

**Comment by jason-gabriele** [comment]
I had the same problem. Adding a report version fixes the issue

**Comment by tomieq** [comment]
Thank you for the feedback. I added `Report Version` header field and released version 1.0.0
