### ISSUE TITLE
Doesn't seem to work anymore with newer version of Xcode 15.0.1/Swift

### ISSUE THREAD

**Issue by danardelean** [tomieq/AppleCrashScripts#5]
I have tried it with :
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)

available in Xcode 15.0.1 and it doesn't seem to work anymore. The error I am getting:

convertFromJson.swift:386:18: warning: type 'Any' is not optional, value can never be nil; this is an error in Swift 6

**Comment by tomieq** [comment]
Thank you for pointing this out. The fix is done.

**Comment by tomieq** [comment]
Marking as closed

**Comment by tomieq** [comment]
Merged
